name: nameof
description: Generator for  Dart class member's names, such as fields, properties, methods, constructors 
version: 0.2.2
homepage: https://github.com/flankb/nameof

environment:
  sdk: '>=2.16.0 <4.0.0'

dependencies:
  analyzer: ^8.1.1
  build: ^4.0.0 
  source_gen: ^4.0.1
  build_config: '>=0.4.4 <2.0.0'
  nameof_annotation: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.11
  build_test: ^3.4.0
  source_gen_test: ^1.0.6
  lints: ^6.0.0
  test: ^1.24.0
