name: example
description: Example for nameof package
version: 1.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ^3.0.0


dependencies:
  nameof_annotation:
    path: ../../nameof_annotation

dev_dependencies:
  lints: ^3.0.0
  build_runner:
  # nameof: ^0.2.0
  nameof:
    path: ../
